// Generated by CoffeeScript 1.8.0
(function() {
  var http, querystring, routeGet, routePost, start, url;

  start = function(route, handle) {
    var onRequest;
    onRequest = function(request, response) {
      var pathname, postData;
      postData = "";
      pathname = url.parse(request.url).pathname;
      console.log("Request for " + pathname + " received.");
      console.log(request.method);
      if (request.method === "POST") {
        request.setEncoding("utf8");
        request.addListener("data", function(postDataChunk) {
          postData += postDataChunk;
        });
        request.addListener("end", function() {
          routePost(handle, pathname, response, postData);
        });
      } else {
        routeGet(handle, pathname, response, request);
      }
    };
    http.createServer(onRequest).listen(8888);
    console.log("Server has started.");
  };

  routeGet = function(handle, pathname, response, request) {
    console.log("About to route a request for " + pathname);
    if (typeof handle[pathname] === "function") {
      handle[pathname](response, request);
    } else {
      console.log("No request handler found for " + pathname);
      response.writeHead(404, {
        "Content-Type": "text/html"
      });
      response.write("404 Not found");
      response.end();
    }
  };

  routePost = function(handle, pathname, response, postData) {
    console.log("About to route a request for " + pathname);
    if (typeof handle[pathname] === "function") {
      handle[pathname](response, postData);
    } else {
      console.log("No request handler found for " + pathname);
      response.writeHead(404, {
        "Content-Type": "text/html"
      });
      response.write("404 Not found");
      response.end();
    }
  };

  http = require("http");

  url = require("url");

  querystring = require("querystring");

  exports.start = start;

  exports.routeGet = routeGet;

  exports.routePost = routePost;

}).call(this);

//# sourceMappingURL=server.js.map
